In [1]:
import torch
origin_pth = torch.load('../checkpoints/effvit/test1/best_b0-r960_cityscapes_os16.pth' ,map_location=torch.device('cuda'))

/home/pdongaa/anaconda3/envs/segmaxformer/lib/python3.8/site-packages/tqdm/auto.py:22: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm


In [6]:
new_state_dict = origin_pth
for k, v in origin_pth.items():
    new_state_dict[k] = v
    
for k in list(new_state_dict["model_state"]):
    if "lsq" in k:
        print(k)
        ori = k
        new_k = ori.replace(".s", ".s.initilized_alpha")
        new_state_dict["model_state"][new_k] = torch.ones(1)
        print(new_k)
        print(new_state_dict["model_state"][new_k])
        # # print(k, )
        # del new_state_dict["state_dict"][ori]

backbone.input_stem.0.conv.lsq_w.s
backbone.input_stem.0.conv.lsq_w.s.initilized_alpha
tensor([1.])
backbone.input_stem.0.conv.lsq_a.s
backbone.input_stem.0.conv.lsq_a.s.initilized_alpha
tensor([1.])
backbone.input_stem.0.act.lsq_a.s
backbone.input_stem.0.act.lsq_a.s.initilized_alpha
tensor([1.])
backbone.input_stem.1.main.depth_conv.conv.lsq_w.s
backbone.input_stem.1.main.depth_conv.conv.lsq_w.s.initilized_alpha
tensor([1.])
backbone.input_stem.1.main.depth_conv.conv.lsq_a.s
backbone.input_stem.1.main.depth_conv.conv.lsq_a.s.initilized_alpha
tensor([1.])
backbone.input_stem.1.main.depth_conv.act.lsq_a.s
backbone.input_stem.1.main.depth_conv.act.lsq_a.s.initilized_alpha
tensor([1.])
backbone.input_stem.1.main.point_conv.conv.lsq_w.s
backbone.input_stem.1.main.point_conv.conv.lsq_w.s.initilized_alpha
tensor([1.])
backbone.input_stem.1.main.point_conv.conv.lsq_a.s
backbone.input_stem.1.main.point_conv.conv.lsq_a.s.initilized_alpha
tensor([1.])
backbone.input_stem.1.main.lsq.s
backbone.in

In [17]:
from hmac import new
from sympy import N


new_state_dict = origin_pth
for k, v in origin_pth.items():
    new_state_dict[k] = v
    
        
# for k in list(new_state_dict["state_dict"]):
#     if "decode_head" in k:
#         print(k)
#         ori = k
#         new_k = ori.replace("decode_head.", "head.")
#         new_state_dict["state_dict"][new_k] = origin_pth["state_dict"][ori]
#         del new_state_dict["state_dict"][ori]


for k in list(new_state_dict["state_dict"]):
    if "norm.weight" in k:
        ori = k
        new_k = ori.replace("norm.weight", "conv.bn_weight")
        new_state_dict["state_dict"][new_k] = origin_pth["state_dict"][ori]
        # print(k, )
        del new_state_dict["state_dict"][ori]
    elif "norm.bias" in k:
        ori = k
        new_k = ori.replace("norm.bias", "conv.bn_bias")
        print(k, new_k)
        new_state_dict["state_dict"][new_k] = origin_pth["state_dict"][ori]
        del new_state_dict["state_dict"][ori]
    elif "norm.running_mean" in k:
        # print(k)
        ori = k
        new_k = ori.replace("norm.running_mean", "conv.running_mean")
        new_state_dict["state_dict"][new_k] = origin_pth["state_dict"][ori]
        del new_state_dict["state_dict"][ori]
    elif "norm.running_var" in k:
        # print(k)
        ori = k
        new_k = ori.replace("norm.running_var", "conv.running_var")
        new_state_dict["state_dict"][new_k] = origin_pth["state_dict"][ori]
        del new_state_dict["state_dict"][ori]
    elif "norm.num_batches_tracked" in k:
        del new_state_dict["state_dict"][k]

for k in list(new_state_dict["state_dict"]):
    if "bn_weight" in k:
        ori = k
        new_k = ori.replace("bn_weight", "norm.weight")
        new_state_dict["state_dict"][new_k] = origin_pth["state_dict"][ori]
    elif "bn_bias" in k:
        ori = k
        new_k = ori.replace("bn_bias", "norm.bias")
        print(k, new_k)
        new_state_dict["state_dict"][new_k] = origin_pth["state_dict"][ori]
    elif "running_mean" in k:
        # print(k)
        ori = k
        new_k = ori.replace("running_mean", "norm.running_mean")
        new_state_dict["state_dict"][new_k] = origin_pth["state_dict"][ori]
    elif "running_var" in k:
        # print(k)
        ori = k
        new_k = ori.replace("running_var", "norm.running_var")
        new_state_dict["state_dict"][new_k] = origin_pth["state_dict"][ori]

backbone.stages.0.op_list.0.main.inverted_conv.norm.bias backbone.stages.0.op_list.0.main.inverted_conv.conv.bn_bias
backbone.stages.0.op_list.0.main.depth_conv.norm.bias backbone.stages.0.op_list.0.main.depth_conv.conv.bn_bias
backbone.stages.0.op_list.0.main.point_conv.norm.bias backbone.stages.0.op_list.0.main.point_conv.conv.bn_bias
backbone.stages.0.op_list.1.main.inverted_conv.norm.bias backbone.stages.0.op_list.1.main.inverted_conv.conv.bn_bias
backbone.stages.0.op_list.1.main.depth_conv.norm.bias backbone.stages.0.op_list.1.main.depth_conv.conv.bn_bias
backbone.stages.0.op_list.1.main.point_conv.norm.bias backbone.stages.0.op_list.1.main.point_conv.conv.bn_bias
backbone.stages.1.op_list.0.main.inverted_conv.norm.bias backbone.stages.1.op_list.0.main.inverted_conv.conv.bn_bias
backbone.stages.1.op_list.0.main.depth_conv.norm.bias backbone.stages.1.op_list.0.main.depth_conv.conv.bn_bias
backbone.stages.1.op_list.0.main.point_conv.norm.bias backbone.stages.1.op_list.0.main.point_c

In [18]:
# net = torch.load('../checkpoints/effvit/quan_b1_full.pth' ,map_location=torch.device('cuda'))
net = new_state_dict
for key, value in list(net['state_dict'].items()):
    if 'qkv' in key or 'aggre' in key: print(key, value.size(), sep=" ")



backbone.stages.2.1.context_module.main.qkv_layers.q.conv.weight torch.Size([64, 64, 1, 1])
backbone.stages.2.1.context_module.main.qkv_layers.k.conv.weight torch.Size([64, 64, 1, 1])
backbone.stages.2.1.context_module.main.qkv_layers.v.conv.weight torch.Size([64, 64, 1, 1])
backbone.stages.2.1.context_module.main.aggreg.q.0.0.weight torch.Size([64, 1, 5, 5])
backbone.stages.2.1.context_module.main.aggreg.k.0.0.weight torch.Size([64, 1, 5, 5])
backbone.stages.2.1.context_module.main.aggreg.v.0.0.weight torch.Size([64, 1, 5, 5])
backbone.stages.2.1.context_module.main.aggreg.q.0.1.weight torch.Size([64, 16, 1, 1])
backbone.stages.2.1.context_module.main.aggreg.k.0.1.weight torch.Size([64, 16, 1, 1])
backbone.stages.2.1.context_module.main.aggreg.v.0.1.weight torch.Size([64, 16, 1, 1])
backbone.stages.2.2.context_module.main.qkv_layers.q.conv.weight torch.Size([64, 64, 1, 1])
backbone.stages.2.2.context_module.main.qkv_layers.k.conv.weight torch.Size([64, 64, 1, 1])
backbone.stages.2.2.c

In [19]:
from torch import ne


for k in list(new_state_dict["state_dict"]):
    if "aggreg" in k:
        print(k)
        if "weight" in k:
            # print(k)
            ori = k
            new_k = ori.replace("weight", "conv.weight")
            print(new_k)
            ori = k
            new_state_dict["state_dict"][new_k] = origin_pth["state_dict"][ori]
            del new_state_dict["state_dict"][ori]
    elif "qkv_layers" in k:
        print(k)
        ori = k
        new_k = ori.replace("conv.", "")
        print(new_k)
        ori = k
        new_state_dict["state_dict"][new_k] = origin_pth["state_dict"][ori]
        del new_state_dict["state_dict"][ori]
        # elif "bias" in k:
        #     print(k)
        #     ori = k
        #     new_k = ori.replace("bias", "conv.bias")
        #     new_state_dict["state_dict"][new_k] = origin_pth["state_dict"][ori]
        #     del new_state_dict["state_dict"][ori]
        # elif "bn_weight" in k:
        #     print(k)
        #     ori = k
        #     new_k = ori.replace("bn_weight", "conv.bn_weight")
        #     new_state_dict["state_dict"][new_k] = origin_pth["state_dict"][ori]
        #     del new_state_dict["state_dict"][ori]
        # elif "bn_bias" in k:
        #     print(k)
        #     ori = k
        #     new_k = ori.replace("bn_bias", "conv.bn_bias")
        #     new_state_dict["state_dict"][new_k] = origin_pth["state_dict"][ori]
        #     del new_state_dict["state_dict"][ori]
        

backbone.stages.2.1.context_module.main.qkv_layers.q.conv.weight
backbone.stages.2.1.context_module.main.qkv_layers.q.weight
backbone.stages.2.1.context_module.main.qkv_layers.k.conv.weight
backbone.stages.2.1.context_module.main.qkv_layers.k.weight
backbone.stages.2.1.context_module.main.qkv_layers.v.conv.weight
backbone.stages.2.1.context_module.main.qkv_layers.v.weight
backbone.stages.2.1.context_module.main.aggreg.q.0.0.weight
backbone.stages.2.1.context_module.main.aggreg.q.0.0.conv.weight
backbone.stages.2.1.context_module.main.aggreg.k.0.0.weight
backbone.stages.2.1.context_module.main.aggreg.k.0.0.conv.weight
backbone.stages.2.1.context_module.main.aggreg.v.0.0.weight
backbone.stages.2.1.context_module.main.aggreg.v.0.0.conv.weight
backbone.stages.2.1.context_module.main.aggreg.q.0.1.weight
backbone.stages.2.1.context_module.main.aggreg.q.0.1.conv.weight
backbone.stages.2.1.context_module.main.aggreg.k.0.1.weight
backbone.stages.2.1.context_module.main.aggreg.k.0.1.conv.weight


In [20]:
torch.save(new_state_dict, '../checkpoints/effvit/quan_b0_full_bn.pth')